### ISSUE TITLE
Publishing Provider to Terraform Registry for community reach

### ISSUE THREAD

**Issue by ggsood** [disaster37/terraform-provider-kibana#1]
Hi @disaster37 

Hope u are doing great, this is a fantastic code you have written to manage kibana objects using terraform, please can you push the provider to official terraform registry which support Terraform 13 features.

I'll be happy to help.

Thanks

**Comment by disaster37** [comment]
It's done: https://registry.terraform.io/providers/disaster37/kibana/latest
