### ISSUE TITLE
should allow set user space ID

### ISSUE THREAD

**Issue by Wing924** [disaster37/terraform-provider-kibana#19]
Current implementation treats Kibana space ID as Kibana space name.
https://github.com/disaster37/terraform-provider-kibana/blob/429066eaa8c38d3b68d5d5c5c342b52d9abf4124/kb/resource_kibana_userspace.go#L66-L73

The space ID only allows `[a-z0-9-_]+`, while the space name allows any chars.
It makes a problem that space name contains chars like space.

**Comment by disaster37** [comment]
Fix on release [7.12.10](https://github.com/disaster37/terraform-provider-kibana/releases/tag/v7.12.10)
