### ISSUE TITLE
Support for kibana 8.0

### ISSUE THREAD

**Issue by CondormanFr** [disaster37/terraform-provider-kibana#26]
Hi,
Elastic released kibana 8.0.
Would it be possible to support this version. I'm recreating cluster from scratch with this new version and you script is very useful.
For the moment, the message is 
`Kibana is older than 7.0.0 `

Thanks

**Comment by rfavreau** [comment]
+1
 I have also updated to Kibana 8.0 and i would be appreciated to be able to continue working with this TF provider.

Thanks for you work.

**Comment by disaster37** [comment]
Hi,

new release is available here to support Kibana 8.x: https://github.com/disaster37/terraform-provider-kibana/releases/tag/v8.0.0
