### ISSUE TITLE
Kibana aws elasticsearch with opendistro Error: 401 Unauthorized

### ISSUE THREAD

**Issue by petrukngantuk** [disaster37/terraform-provider-kibana#7]
Hi @disaster37 @ggsood , hope you doing well,

any plan to make this support kibana with opendistro authentication?,
I struggle create index-pattern using terraform with kibana api support,

thanks!

**Comment by arash-bizcover** [comment]
Hi 

Trying to connect to Kibana provided by AWS elasticsearch. 
Elasticsearch version7.1

No user pass set:
```hcl
 provider "kibana" {
    url     = "https://vpc-nonprod-logs-XXXXXXXXXX.ap-southeast-2.es.amazonaws.com:443"
}
```

``` 
Error: 403 Forbidden

  on vars.tf line 1, in provider "kibana":
   1: provider "kibana" {
 ```
